
- id: browser_features
  name: Browser Features
  codeName: browser_features
  type: object
  code: |
    {
      user_agent: navigator.userAgent,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      audio_context: (() => {
        try {
          return !!(window.AudioContext || window.webkitAudioContext);
        } catch (e) {
          return false;
        }
      })(),
      localStorage: !!window.localStorage,
      sessionStorage: !!window.sessionStorage,
      indexedDB: !!window.indexedDB,
      webWorker: !!window.Worker,
      webGL: !!window.WebGLRenderingContext,
      permissionsApi: !!navigator.permissions,
      languages: navigator.languages || [],
      doNotTrack: navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack || 'Not available',
      plugins: Array.from(navigator.plugins).map((p) => p.name)
    }
  description: Core browser features and capabilities
  abuse_indication:
    bot: Mismatches or inconsistencies in browser features can indicate automation. Bots may have missing or unusual combinations of features.
  category: browser
  outputs:
    user_agent:
      name: User Agent
      type: string
      description: The browser's user agent string that identifies the browser and system
    timezone:
      name: Time Zone
      type: string
      description: The time zone setting of the browser
    audio_context:
      name: Audio Context Available
      type: boolean
      description: Whether the browser supports audio processing capabilities
    localStorage:
      name: Local Storage
      type: boolean
      description: Whether the browser supports localStorage
    sessionStorage:
      name: Session Storage
      type: boolean
      description: Whether the browser supports sessionStorage
    indexedDB:
      name: IndexedDB
      type: boolean
      description: Whether the browser supports indexedDB
    webWorker:
      name: Web Worker
      type: boolean
      description: Whether the browser supports Web Workers
    webGL:
      name: WebGL
      type: boolean
      description: Whether the browser supports WebGL
    permissionsApi:
      name: Permissions API
      type: boolean
      description: Whether the browser supports the Permissions API
    languages:
      name: Browser Languages
      type: array
      description: List of configured browser languages
    doNotTrack:
      name: Do Not Track Setting
      type: string
      description: Browser's Do Not Track preference
    plugins:
      name: Browser Plugins
      type: array
      description: List of installed browser plugins
