- id: browser_features
  name: Browser Features
  codeName: browser_features
  type: object
  code: |
    {
      user_agent: navigator.userAgent,
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      audio_context: (() => {
        try {
          return !!(window.AudioContext || window.webkitAudioContext);
        } catch (e) {
          return false;
        }
      })(),
    }
  description: Core browser features and capabilities
  abuse_indication:
    bot: Mismatches or inconsistencies in browser features can indicate automation. Bots may have missing or unusual combinations of features.
  category: browser
  outputs:
    user_agent:
      name: User Agent
      type: string
      description: The browser's user agent string that identifies the browser and system
    timezone:
      name: Time Zone
      type: string
      description: The time zone setting of the browser
    audio_context:
      name: Audio Context Available
      type: boolean
      description: Whether the browser supports audio processing capabilities
