
- id: clientjs_fingerprint
  name: ClientJS Fingerprint
  codeName: clientjs_fingerprint
  type: object
  code: |
    async () => {
      const fp = await new ClientJS();
      return {
        browser: {
          name: fp.getBrowser(),
          version: fp.getBrowserVersion(),
          engine: fp.getEngine(),
          engineVersion: fp.getEngineVersion(),
        },
        device: {
          os: fp.getOS(),
          osVersion: fp.getOSVersion(),
          device: fp.getDevice(),
          deviceType: fp.getDeviceType(),
          deviceVendor: fp.getDeviceVendor(),
        },
        fingerprint: fp.getFingerprint(),
        // isIncognito method is not available, so we'll remove it
        browserSpoofed: fp.getBrowserMajorVersion() !== parseInt(fp.getBrowser().split(' ')[1]),
      };
    }
  description: Comprehensive browser and device fingerprinting using ClientJS
  abuse_indication:
    bot: Combined fingerprinting data can reveal patterns of automated behavior, spoofed browsers, and virtual environments.
  category: fingerprinting
  dependency: clientjs
  outputs:
    browser:
      name: Browser Information
      type: object
      description: Detailed browser information
      outputs:
        name:
          name: Browser Name
          type: string
          description: The name of the browser being used
          abuse_indication:
            bot: Unusual browser names or known automation tools like PhantomJS, Selenium WebDriver can directly indicate bot activity.
        version:
          name: Browser Version
          type: string
          description: The version of the browser
          abuse_indication:
            bot: Outdated or inconsistent versions compared to other features can reveal spoofed browsers or automation tools.
        engine:
          name: Browser Engine
          type: string
          description: The browser's rendering engine
          abuse_indication:
            bot: Mismatches between engine and browser version can indicate spoofed or automated browsers.
        engineVersion:
          name: Engine Version
          type: string
          description: The version of the browser engine
          abuse_indication:
            bot: Inconsistent engine versions compared to the browser version can reveal automated or spoofed browsers.
    device:
      name: Device Information
      type: object
      description: Information about the device and operating system
      outputs:
        os:
          name: Operating System
          type: string
          description: The operating system name
          abuse_indication:
            bot: Server operating systems or Linux distributions commonly used in cloud environments can indicate automated traffic.
        osVersion:
          name: OS Version
          type: string
          description: The operating system version
          abuse_indication:
            bot: Outdated or unusual OS versions, especially in combination with modern browser versions, can indicate virtualized environments.
        device:
          name: Device
          type: string
          description: The device name
          abuse_indication:
            bot: Generic device names or those commonly used in virtual machines can indicate automated environments.
        deviceType:
          name: Device Type
          type: string
          description: The type of device (desktop, mobile, tablet)
          abuse_indication:
            bot: Mismatches between device type and other characteristics (like touch support) can reveal emulated environments.
        deviceVendor:
          name: Device Vendor
          type: string
          description: The manufacturer of the device
          abuse_indication:
            bot: Generic or missing vendor information can indicate virtual or emulated devices.
    fingerprint:
      name: Fingerprint Hash
      type: string
      description: Unique hash generated from browser characteristics
      abuse_indication:
        bot: Rapidly changing fingerprints or patterns in fingerprint generation can indicate bot rotation or spoofing attempts.
    browserSpoofed:
      name: Browser Spoofed
      type: boolean
      description: Whether the browser information shows signs of spoofing
      abuse_indication:
        bot: Direct indicator of browser spoofing, commonly used in bot activity to mask true identity.
