
- id: cpu_cores
  name: CPU Cores
  codeName: cpu_cores
  type: number
  code: |
    navigator.hardwareConcurrency || 0
  description: Number of logical processors available to the browser
  abuse_indication:
    bot: Virtual environments and containers often have unusual core counts. Low core counts or inconsistencies with other hardware info can indicate virtualized environments.
  category: hardware
