
- id: fingerprint
  name: Browser Fingerprint
  codeName: fingerprint
  type: object
  code: |
    async () => {
      const fp = await FingerprintJS.load();
      const result = await fp.get();
      const canvas = document.createElement('canvas');
      canvas.width = 240;
      canvas.height = 60;
      const ctx = canvas.getContext('2d');
      const canvasData = ctx ? (() => {
        ctx.fillText('BotWhisperer', 10, 50);
        return canvas.toDataURL();
      })() : null;
      
      return {
        visitorId: result.visitorId,
        confidence: result.confidence.score,
        userAgent: result.components.userAgent,
        webDriver: result.components.webDriver,
        language: result.components.language,
        platform: result.components.platform,
        touchSupport: result.components.touchSupport,
        canvas: canvasData,
        audioContext: !!(window.AudioContext || window.webkitAudioContext),
        consistentId: result.visitorId
      };
    }
  description: Comprehensive browser fingerprinting data including visitor identification and system capabilities
  abuse_indication:
    bot: Fingerprint consistency patterns, component combinations, visitor ID changes, and unusual platform/language combinations can reveal automated behavior
  category: fingerprinting
  dependency: fingerprintjs
  outputs:
    visitorId:
      name: Visitor ID
      type: string
      description: Unique visitor identifier
      abuse_indication:
        bot: Rapidly changing visitor IDs or patterns in ID generation can indicate bot rotation or spoofing attempts.
    confidence:
      name: Confidence Score
      type: number
      description: Fingerprint confidence score
      abuse_indication:
        bot: Low confidence scores often indicate spoofed or inconsistent browser characteristics.
    userAgent:
      name: User Agent
      type: string
      description: Browser user agent string
      abuse_indication:
        bot: Inconsistencies between user agent and actual browser capabilities can reveal spoofed environments.
    webDriver:
      name: Web Driver
      type: boolean
      description: Selenium/automation detection
      abuse_indication:
        bot: Direct indicator of automation - presence of webdriver suggests Selenium or similar automation tools.
    language:
      name: Language
      type: string
      description: Browser language
      abuse_indication:
        bot: Mismatches between language settings and IP geolocation can indicate automated traffic.
    platform:
      name: Platform
      type: string
      description: Operating system platform
      abuse_indication:
        bot: Inconsistencies between platform and other system characteristics can reveal virtualized environments.
    touchSupport:
      name: Touch Support Details
      type: object
      description: Touch support capabilities
      abuse_indication:
        bot: Mismatched touch capabilities compared to claimed device type can indicate emulated environments.
    canvas:
      name: Canvas Fingerprint
      type: string
      description: Rendering-based fingerprint
    audioContext:
      name: Audio Context
      type: boolean
      description: Audio processing capability
    consistentId:
      name: Consistent ID
      type: string
      description: Stable visitor identifier across sessions

