
- id: has_permissions_api
  name: Permissions API Available
  codeName: has_permissions_api
  type: boolean
  code: |
    !!navigator.permissions
  description: Whether the browser supports the Permissions API
  abuse_indication:
    bot: Automated browsers may lack modern browser APIs. The absence of the Permissions API in an otherwise modern browser profile can indicate spoofing.
  category: browser
