
detectionFeatures:
  - id: browser_info
    name: Browser Information
    codeName: browser_info
    type: object
    code: "(() => { const fp = new ClientJS(); return { browser: fp.getBrowser(), browserVersion: fp.getBrowserVersion(), engine: fp.getEngine(), engineVersion: fp.getEngineVersion() }; })()"
    description: Information about the browser type, version, and rendering engine
    abuse_indication:
      bot: Browser information can reveal automated browsers, headless browsers, or spoofed user agents commonly used by bots. Inconsistencies between browser version and features can indicate fake browsers.
    category: browser
    dependency: clientjs
    outputs:
      browser:
        name: Browser Name
        type: string
        description: The name of the browser being used
      browserVersion:
        name: Browser Version
        type: string
        description: The version of the browser
      engine:
        name: Browser Engine
        type: string
        description: The browser's rendering engine
      engineVersion:
        name: Engine Version
        type: string
        description: The version of the browser engine

  - id: device_info
    name: Device Information
    codeName: device_info
    type: object
    code: "(() => { const fp = new ClientJS(); return { os: fp.getOS(), osVersion: fp.getOSVersion(), device: fp.getDevice(), deviceType: fp.getDeviceType(), deviceVendor: fp.getDeviceVendor() }; })()"
    description: Information about the user's device hardware and operating system
    abuse_indication:
      bot: Device characteristics can expose virtual machines, emulators, or cloud environments commonly used for automation. Mismatches between OS and device information may indicate spoofing.
    category: hardware
    dependency: clientjs
    outputs:
      os:
        name: Operating System
        type: string
        description: The operating system name
      osVersion:
        name: OS Version
        type: string
        description: The operating system version
      device:
        name: Device
        type: string
        description: The device name
      deviceType:
        name: Device Type
        type: string
        description: The type of device (desktop, mobile, tablet)
      deviceVendor:
        name: Device Vendor
        type: string
        description: The manufacturer of the device

  - id: screen_info
    name: Screen Information
    codeName: screen_info
    type: object
    code: "{ width: screen.width, height: screen.height, colorDepth: screen.colorDepth, pixelRatio: window.devicePixelRatio }"
    description: Technical specifications of the user's display screen
    abuse_indication:
      bot: Unusual screen resolutions, color depths, or pixel ratios can identify virtualized environments. Bots often use standard resolutions or have inconsistent screen properties.
    category: hardware
    outputs:
      width:
        name: Screen Width
        type: number
        description: The width of the screen in pixels
      height:
        name: Screen Height
        type: number
        description: The height of the screen in pixels
      colorDepth:
        name: Color Depth
        type: number
        description: The color depth of the screen
      pixelRatio:
        name: Device Pixel Ratio
        type: number
        description: The ratio between physical pixels and logical pixels

  - id: fingerprint_data
    name: Fingerprint Data
    codeName: fingerprint_data
    type: object
    code: "(async () => { const fp = await FingerprintJS.load(); const result = await fp.get(); return { visitorId: result.visitorId, confidence: result.confidence.score, userAgent: result.components.userAgent, webDriver: result.components.webDriver, language: result.components.language, platform: result.components.platform, touchSupport: result.components.touchSupport }; })()"
    description: Comprehensive browser fingerprinting data used for visitor identification
    abuse_indication:
      bot: Fingerprint consistency across sessions can reveal automated behavior. Low confidence scores, presence of webDriver, or unusual platform combinations often indicate bot activity.
    category: fingerprinting
    dependency: fingerprintjs
    outputs:
      visitorId:
        name: Visitor ID
        type: string
        description: Unique visitor identifier
      confidence:
        name: Confidence Score
        type: number
        description: Confidence score of the fingerprint
      userAgent:
        name: User Agent
        type: string
        description: Browser user agent string
      webDriver:
        name: Web Driver
        type: boolean
        description: Whether web driver is available
      language:
        name: Language
        type: string
        description: Browser language
      platform:
        name: Platform
        type: string
        description: Operating system platform
      touchSupport:
        name: Touch Support Details
        type: object
        description: Touch support capabilities
        outputs:
          maxTouchPoints:
            name: Max Touch Points
            type: number
            description: Maximum number of touch points supported
          touchEvent:
            name: Touch Event Support
            type: boolean
            description: Whether touch events are supported
          touchStart:
            name: Touch Start Support
            type: boolean
            description: Whether touchstart event is supported

  - id: user_agent
    name: User Agent
    codeName: user_agent
    type: string
    code: "navigator.userAgent"
    description: The browser's user agent string that identifies the browser and system
    abuse_indication:
      bot: Bots frequently use fake or inconsistent user agents. Common indicators include outdated versions, unusual combinations of browser and OS, or known bot signatures.
    category: browser
    
  - id: browser_languages
    name: Browser Languages
    codeName: browser_languages
    type: array
    code: "navigator.languages || []"
    description: List of language preferences configured in the browser
    abuse_indication:
      bot: Bots often have missing or misconfigured language settings. Unusual language combinations or single language settings can indicate automated browsers.
    category: browser
    
  - id: timezone
    name: Time Zone
    codeName: timezone
    type: string
    code: "Intl.DateTimeFormat().resolvedOptions().timeZone"
    description: The time zone setting of the browser
    abuse_indication:
      bot: Mismatches between timezone and IP geolocation can indicate VPN usage or bot networks. Bots may use default UTC or have inconsistent timezone settings.
    category: browser
    
  - id: browser_plugins
    name: Browser Plugins
    codeName: browser_plugins
    type: array
    code: "Array.from(navigator.plugins).map(p => p.name)"
    description: List of browser plugins installed and enabled
    abuse_indication:
      bot: Automated browsers typically have no plugins or a very limited set. The absence of common plugins or unusual plugin combinations can indicate bot activity.
    category: browser
    
  - id: webgl_renderer
    name: WebGL Renderer
    codeName: webgl_renderer
    type: string
    code: "(() => { const canvas = document.createElement('canvas'); const gl = canvas.getContext('webgl'); return gl && gl.getExtension('WEBGL_debug_renderer_info') ? gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info').UNMASKED_RENDERER_WEBGL) : null; })()"
    description: Information about the graphics hardware and WebGL capabilities
    abuse_indication:
      bot: Virtual or headless environments often have basic or software-rendered WebGL. Unusual renderer strings or missing WebGL support can indicate automated browsers.
    category: hardware
    
  - id: canvas_fingerprint
    name: Canvas Fingerprint
    codeName: canvas_fingerprint
    type: string
    code: "(() => { const canvas = document.createElement('canvas'); canvas.width = 240; canvas.height = 60; const ctx = canvas.getContext('2d'); if (ctx) { ctx.fillText('BotWhisperer', 10, 50); return canvas.toDataURL(); } return null; })()"
    description: Unique identifier based on canvas rendering differences
    abuse_indication:
      bot: Automated browsers often produce identical canvas fingerprints or fail to render properly. Variations in anti-aliasing and font rendering can expose headless browsers.
    category: fingerprinting
    
  - id: cpu_cores
    name: CPU Cores
    codeName: cpu_cores
    type: number
    code: "navigator.hardwareConcurrency || 0"
    description: Number of logical processors available to the browser
    abuse_indication:
      bot: Virtual environments and containers often have unusual core counts. Low core counts or inconsistencies with other hardware info can indicate virtualized environments.
    category: hardware
    
  - id: device_memory
    name: Device Memory
    codeName: device_memory
    type: number
    code: "(() => { try { return navigator.deviceMemory || 0; } catch(e) { return 0; } })()"
    description: Amount of RAM memory available to the browser
    abuse_indication:
      bot: Automated environments often report standard or limited memory values. Inconsistencies between memory and other hardware indicators can reveal virtualization.
    category: hardware
    
  - id: has_touch_support
    name: Touch Support
    codeName: has_touch_support
    type: boolean
    code: "('ontouchstart' in window)"
    description: Whether the device supports touch input
    abuse_indication:
      bot: Desktop automation tools might incorrectly report touch capabilities. Mismatches between device type and touch support can indicate spoofing.
    category: hardware
    
  - id: network_info
    name: Network Information
    codeName: network_info
    type: object
    code: "(() => { try { return navigator.connection ? { effectiveType: navigator.connection.effectiveType, rtt: navigator.connection.rtt } : { effectiveType: 'unknown', rtt: 0 }; } catch(e) { return { effectiveType: 'unknown', rtt: 0 }; } })()"
    description: Information about the network connection type and quality
    abuse_indication:
      bot: Data center networks used by bots often have distinctive characteristics. Unusual network patterns or consistently perfect conditions may indicate automated traffic.
    category: network
    outputs:
      effectiveType:
        name: Connection Type
        type: string
        description: The effective connection type (4g, 3g, 2g, slow-2g)
      rtt:
        name: Round Trip Time
        type: number
        description: The estimated round-trip time of the current connection
    
  - id: browser_features
    name: Browser Features
    codeName: browser_features
    type: object
    code: "{ localStorage: !!window.localStorage, sessionStorage: !!window.sessionStorage, indexedDB: !!window.indexedDB, webWorker: !!window.Worker, webGL: !!window.WebGLRenderingContext }"
    description: Support status for various browser APIs and features
    abuse_indication:
      bot: Headless browsers and automation tools often lack support for modern features. Unusual combinations of supported and unsupported features can reveal bot environments.
    category: browser
    outputs:
      localStorage:
        name: Local Storage
        type: boolean
        description: Whether the browser supports localStorage
      sessionStorage:
        name: Session Storage
        type: boolean
        description: Whether the browser supports sessionStorage
      indexedDB:
        name: IndexedDB
        type: boolean
        description: Whether the browser supports indexedDB
      webWorker:
        name: Web Worker
        type: boolean
        description: Whether the browser supports Web Workers
      webGL:
        name: WebGL
        type: boolean
        description: Whether the browser supports WebGL
    
  - id: has_audio_context
    name: Audio Context Available
    codeName: has_audio_context
    type: boolean
    code: "(() => { try { return !!(window.AudioContext || window.webkitAudioContext); } catch (e) { return false; } })()"
    description: Whether the browser supports audio processing capabilities
    abuse_indication:
      bot: Headless browsers and basic automation tools often lack audio support. Missing or limited audio capabilities can indicate non-standard browser environments.
    category: fingerprinting
    
  - id: has_permissions_api
    name: Permissions API Available
    codeName: has_permissions_api
    type: boolean
    code: "!!navigator.permissions"
    description: Whether the browser supports the Permissions API
    abuse_indication:
      bot: Automated browsers may lack modern browser APIs. The absence of the Permissions API in an otherwise modern browser profile can indicate spoofing.
    category: browser
    
  - id: do_not_track
    name: Do Not Track Setting
    codeName: do_not_track
    type: string
    code: "(() => { try { return navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack || 'Not available'; } catch(e) { return 'Not available'; } })()"
    description: The browser's Do Not Track preference setting
    abuse_indication:
      bot: Most users don't modify this setting. Unusual patterns in DNT settings across multiple requests can indicate automated behavior.
    category: browser
    
  - id: has_battery_api
    name: Battery API Available
    codeName: has_battery_api
    type: boolean
    code: "(() => { try { return !!navigator.getBattery; } catch(e) { return false; } })()"
    description: Whether the browser supports the Battery Status API
    abuse_indication:
      bot: Virtual environments and automation tools often lack battery information. The absence of battery API in mobile user agents can indicate spoofing.
    category: hardware
    
  - id: visitor_id
    name: visitor_id
    codeName: visitor_id
    type: string
    code: "(async () => { const fp = await FingerprintJS.load(); const result = await fp.get(); return result.visitorId; })()"
    description: Unique identifier generated by FingerprintJS for visitor tracking
    abuse_indication:
      bot: Rapidly changing visitor IDs or patterns in ID generation can indicate bot rotation or spoofing attempts.
    category: fingerprinting
    dependency: fingerprintjs

  - id: is_incognito
    name: is_incognito
    codeName: is_incognito
    type: boolean
    code: "(() => { const fp = new ClientJS(); return fp.isIncognito(); })()"
    description: Detects if the browser is in private browsing mode
    abuse_indication:
      bot: While not definitive, high rates of incognito usage combined with other suspicious patterns may indicate automated browsing.
    category: browser
    dependency: clientjs

  - id: is_browser_spoofed
    name: is_browser_spoofed
    codeName: is_browser_spoofed
    type: boolean
    code: "(() => { const fp = new ClientJS(); return fp.getBrowserMajorVersion() !== parseInt(fp.getBrowser().split(' ')[1]); })()"
    description: Checks if the reported browser information shows signs of spoofing
    abuse_indication:
      bot: Direct indicator of browser spoofing, commonly used in bot activity to mask true identity.
    category: fingerprinting
    dependency: clientjs

  - id: browser_fingerprint
    name: browser_fingerprint
    codeName: browser_fingerprint
    type: string
    code: "(() => { const fp = new ClientJS(); return fp.getFingerprint(); })()"
    description: Hash generated from various browser characteristics
    abuse_indication:
      bot: Identical fingerprints across different sessions or rapid fingerprint changes can indicate bot farms or automated browsing.
    category: fingerprinting
    dependency: clientjs

# ... keep existing code (fingerprintingLibraries section remains unchanged)

