
- id: headless_feature_consistency
  name: Feature Consistency
  codeName: headless_feature_consistency
  type: object
  code: |
    (() => {
      return {
        noWebGL: (() => {
          try {
            const canvas = document.createElement('canvas');
            return !canvas.getContext('webgl') && !canvas.getContext('experimental-webgl');
          } catch (e) {
            return true;
          }
        })(),
        noWebRTC: !('RTCPeerConnection' in window),
        noCanvas: (() => {
          try {
            document.createElement('canvas').getContext('2d');
            return false;
          } catch (e) {
            return true;
          }
        })()
      };
    })()
  description: Browser feature consistency checks
  category: browser
  outputs:
    noWebGL:
      name: WebGL Missing
      type: boolean
      description: WebGL context unavailable
      abuse_indication:
        bot: Headless browsers often lack WebGL support
    noWebRTC:
      name: WebRTC Missing
      type: boolean
      description: WebRTC support missing
      abuse_indication:
        bot: Headless browsers often lack WebRTC support
    noCanvas:
      name: Canvas Missing
      type: boolean
      description: Canvas context unavailable
      abuse_indication:
        bot: Headless browsers often have limited canvas support
