
- id: headless_hardware_indicators
  name: Hardware Indicators
  codeName: headless_hardware_indicators
  type: object
  code: |
    (() => {
      return {
        noGPU: (() => {
          const canvas = document.createElement('canvas');
          const gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl');
          if (!gl) return true;
          const debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
          return !debugInfo || !gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL);
        })(),
        noMedia: !('mediaDevices' in navigator),
        noGamepads: !('getGamepads' in navigator)
      };
    })()
  description: Hardware-related headless detection
  category: hardware
  outputs:
    noGPU:
      name: No GPU Info
      type: boolean
      description: Missing GPU information
      abuse_indication:
        bot: Headless browsers often lack GPU information
    noMedia:
      name: No Media Devices
      type: boolean
      description: No media devices available
      abuse_indication:
        bot: Missing media devices can indicate headless environments
    noGamepads:
      name: No Gamepad Support
      type: boolean
      description: No gamepad API support
      abuse_indication:
        bot: Limited hardware API support suggests automated environment
