
- id: webgl_renderer
  name: WebGL Renderer
  codeName: webgl_renderer
  type: string
  code: |
    (() => {
      const canvas = document.createElement('canvas');
      const gl = canvas.getContext('webgl');
      return gl && gl.getExtension('WEBGL_debug_renderer_info')
        ? gl.getParameter(gl.getExtension('WEBGL_debug_renderer_info').UNMASKED_RENDERER_WEBGL)
        : null;
    })()
  description: Information about the graphics hardware and WebGL capabilities
  abuse_indication:
    bot: Virtual or headless environments often have basic or software-rendered WebGL. Unusual renderer strings or missing WebGL support can indicate automated browsers.
  category: hardware
