
- id: network_info
  name: Network Information
  codeName: network_info
  type: object
  code: |
    (() => {
      try {
        return navigator.connection
          ? {
              effectiveType: navigator.connection.effectiveType,
              rtt: navigator.connection.rtt,
            }
          : {
              effectiveType: 'unknown',
              rtt: 0,
            };
      } catch (e) {
        return {
          effectiveType: 'unknown',
          rtt: 0,
        };
      }
    })()
  description: Information about the network connection type and quality
  abuse_indication:
    bot: Data center networks used by bots often have distinctive characteristics. Unusual network patterns or consistently perfect conditions may indicate automated traffic.
  category: network
  outputs:
    effectiveType:
      name: Connection Type
      type: string
      description: The effective connection type (4g, 3g, 2g, slow-2g)
      abuse_indication:
        bot: Consistently poor connection types or those associated with data centers can indicate bot activity.
    rtt:
      name: Round Trip Time
      type: number
      description: The estimated round-trip time of the current connection
      abuse_indication:
        bot: Extremely low or stable RTT values can indicate connections within a data center, common for bots.
