clientjs_fingerprint:
  name: ClientJS Fingerprint
  codeName: clientjs_fingerprint
  type: object
  exemplaryValues:
    - {
        browser:
          {
            name: "Chrome",
            version: "120.0.6099.130",
            engine: "Blink",
            engineVersion: "120.0.6099.130",
          },
        device:
          {
            os: "Windows",
            osVersion: "10.0",
            device: "Desktop",
            deviceType: "desktop",
            deviceVendor: "Dell",
          },
        fingerprint: 1922925364,
        browserSpoofed: false,
      }
    - {
        browser:
          {
            name: "Firefox",
            version: "122.0",
            engine: "Gecko",
            engineVersion: "20240201",
          },
        device:
          {
            os: "macOS",
            osVersion: "14.2.1",
            device: "MacBook Pro",
            deviceType: "desktop",
            deviceVendor: "Apple",
          },
        fingerprint: 3222925364,
        browserSpoofed: false,
      }
    - {
        browser:
          {
            name: "HeadlessChrome",
            version: "120.0.6099.130",
            engine: "Blink",
            engineVersion: "120.0.6099.130",
          },
        device:
          {
            os: "Linux",
            osVersion: "5.15.0",
            device: "Generic",
            deviceType: "desktop",
            deviceVendor: "Generic",
          },
        fingerprint: 1933125364,
        browserSpoofed: true,
      }
  code: |
    async () => {
      const fp = await new ClientJS();
      return {
        browser: {
          name: fp.getBrowser(),
          version: fp.getBrowserVersion(),
          engine: fp.getEngine(),
          engineVersion: fp.getEngineVersion(),
        },
        device: {
          os: fp.getOS(),
          osVersion: fp.getOSVersion(),
          device: fp.getDevice(),
          deviceType: fp.getDeviceType(),
          deviceVendor: fp.getDeviceVendor(),
        },
        fingerprint: fp.getFingerprint(),
        // isIncognito method is not available, so we'll remove it
        browserSpoofed: fp.getBrowserMajorVersion() !== parseInt(fp.getBrowser().split(' ')[1]),
      };
    }
  description: |
    Advanced browser and device fingerprinting implementation using ClientJS library for sophisticated automation detection.
    The system performs comprehensive analysis of browser characteristics through user agent parsing (navigator.userAgent),
    feature detection (navigator.platform, navigator.vendor), and behavioral pattern analysis (timing, API interaction).
    Key detection methods include:
    1) Sophisticated browser identification with version parsing (major.minor.build) and spoofing detection through user agent analysis and feature verification
    2) Rendering engine fingerprinting (WebKit, Gecko, Blink) with version consistency checks and engine-specific API validation
    3) Operating system detection with version parsing (major.minor.build) and platform-specific capability verification
    4) Device type classification through screen characteristics (screen.width/height), touch support analysis (navigator.maxTouchPoints), and hardware information
    5) Multi-component fingerprint generation combining browser, device, and system characteristics
    6) Browser spoofing detection through version comparison (parseInt vs split), engine verification, and feature consistency analysis
    All checks are performed synchronously to prevent timing-based evasion and ensure maximum detection reliability.
  abuseIndication:
    bot: |
      Automated environments typically exhibit specific patterns that differ from legitimate browsers.
      Browser version mismatches with engine version (browserSpoofed = true) indicate sophisticated automation.
      Server operating systems (e.g., Linux) claiming desktop browser capabilities suggest automated environment.
      Generic device names (e.g., 'Generic' or missing vendor information) indicate potential automation.
      Outdated operating systems (e.g., Windows 7) with modern browser versions (e.g., Chrome 100+) suggest automated browser.
      Fingerprint changes occurring more frequently than every 5 minutes indicate potential automation.
  dependency: clientjs
  outputs:
    browser:
      name: Browser Analysis
      type: object
      exemplaryValues:
        - {
            name: "Chrome",
            version: "120.0.6099.130",
            engine: "Blink",
            engineVersion: "120.0.6099.130",
          }
        - {
            name: "Firefox",
            version: "122.0",
            engine: "Gecko",
            engineVersion: "20240201",
          }
        - {
            name: "HeadlessChrome",
            version: "120.0.6099.130",
            engine: "Blink",
            engineVersion: "120.0.6099.130",
          }
      description: |
        Sophisticated browser identification and analysis system.
        Combines user agent parsing (navigator.userAgent), feature detection (navigator.platform), and engine verification for comprehensive browser fingerprinting.
        Verifies version consistency (major.minor.build), engine compatibility, and feature support claims.
      abuseIndication:
        bot: |
          Browser name containing 'PhantomJS' or 'HeadlessChrome' indicates automated browser.
          Version claiming Chrome 100+ on unsupported platforms suggests automated environment.
          Engine version inconsistent with browser version indicates potential automation.
      outputs:
        name:
          name: Browser Name Analysis
          type: string
          exemplaryValues:
            - "Chrome"
            - "Firefox"
            - "Safari"
            - "HeadlessChrome"
            - "PhantomJS"
          description: |
            Advanced browser name extraction and verification system.
            Combines user agent parsing (navigator.userAgent), feature detection (navigator.vendor), and engine identification.
            Expected to match known browser patterns (Chrome, Firefox, Safari) with natural variations.
          abuseIndication:
            bot: |
              Browser name containing 'PhantomJS' or 'HeadlessChrome' indicates automated browser.
              Name containing 'Selenium' or 'WebDriver' suggests automated environment.
              Generic or missing browser name indicates potential automation.
        version:
          name: Version Analysis
          type: string
          exemplaryValues:
            - "120.0.6099.130"
            - "122.0"
            - "17.2.1"
            - "100.0.0"
            - "invalid_version"
          description: |
            Sophisticated version extraction and verification system.
            Analyzes major and minor version components (major.minor.build), build numbers, and release channels.
            Expected to show natural version progression and platform compatibility.
          abuseIndication:
            bot: |
              Version claiming Chrome 100+ on Windows 7 indicates automated browser.
              Version inconsistent with engine version suggests automated environment.
              Missing or invalid version format indicates potential automation.
        engine:
          name: Engine Analysis
          type: string
          exemplaryValues:
            - "Blink"
            - "Gecko"
            - "WebKit"
            - "Generic"
            - "Unknown"
          description: |
            Advanced rendering engine identification system.
            Combines user agent parsing, feature detection (navigator.vendor), and engine-specific API validation.
            Expected to match known engine patterns (WebKit, Gecko, Blink) with platform-specific variations.
          abuseIndication:
            bot: |
              Engine claiming 'WebKit' with Chrome browser indicates automated browser.
              Engine inconsistent with browser name suggests automated environment.
              Generic or missing engine name indicates potential automation.
        engineVersion:
          name: Engine Version Analysis
          type: string
          exemplaryValues:
            - "120.0.6099.130"
            - "20240201"
            - "612.1.29"
            - "invalid_version"
            - "unknown"
          description: |
            Sophisticated engine version verification system.
            Analyzes version components (major.minor.build), compatibility markers, and feature support.
            Expected to show natural version progression and browser compatibility.
          abuseIndication:
            bot: |
              Engine version inconsistent with browser version indicates automated browser.
              Version claiming WebKit 537.36 with Chrome 100+ suggests automated environment.
              Missing or invalid version format indicates potential automation.
    device:
      name: Device Analysis
      type: object
      exemplaryValues:
        - {
            os: "Windows",
            osVersion: "10.0",
            device: "Desktop",
            deviceType: "desktop",
            deviceVendor: "Dell",
          }
        - {
            os: "macOS",
            osVersion: "14.2.1",
            device: "MacBook Pro",
            deviceType: "desktop",
            deviceVendor: "Apple",
          }
        - {
            os: "Linux",
            osVersion: "5.15.0",
            device: "Generic",
            deviceType: "desktop",
            deviceVendor: "Generic",
          }
      description: |
        Comprehensive device and operating system analysis system.
        Combines platform detection (navigator.platform), hardware information (navigator.hardwareConcurrency), and capability verification.
        Verifies device type consistency, vendor information, and OS compatibility.
      abuseIndication:
        bot: |
          Operating system claiming Linux with desktop browser indicates automated browser.
          Device type inconsistent with capabilities suggests automated environment.
          Generic vendor information indicates potential automation.
      outputs:
        os:
          name: OS Analysis
          type: string
          exemplaryValues:
            - "Windows"
            - "macOS"
            - "Linux"
            - "Android"
            - "iOS"
            - "Generic"
          description: |
            Advanced operating system identification system.
            Combines user agent parsing, platform detection (navigator.platform), and OS-specific API validation.
            Expected to show natural OS patterns (Windows, macOS, Linux) with version-specific variations.
          abuseIndication:
            bot: |
              OS claiming Linux with desktop browser indicates automated browser.
              OS inconsistent with browser version suggests automated environment.
              Generic or missing OS name indicates potential automation.
        osVersion:
          name: OS Version Analysis
          type: string
          exemplaryValues:
            - "10.0"
            - "14.2.1"
            - "5.15.0"
            - "13.3.1"
            - "invalid_version"
          description: |
            Sophisticated OS version verification system.
            Analyzes version components (major.minor.build), build numbers, and platform capabilities.
            Expected to show natural version progression and hardware compatibility.
          abuseIndication:
            bot: |
              OS version claiming Windows 7 with Chrome 100+ indicates automated browser.
              Version inconsistent with hardware capabilities suggests automated environment.
              Missing or invalid version format indicates potential automation.
        device:
          name: Device Analysis
          type: string
          exemplaryValues:
            - "Desktop"
            - "MacBook Pro"
            - "iPhone"
            - "Generic"
            - "VMware Virtual Platform"
          description: |
            Advanced device identification system.
            Combines hardware information (navigator.hardwareConcurrency), screen characteristics (screen.width/height), and capability detection.
            Expected to show specific device patterns with natural variations.
          abuseIndication:
            bot: |
              Device name containing 'Generic' or 'VMware' indicates automated browser.
              Device inconsistent with capabilities suggests automated environment.
              Missing or invalid device information indicates potential automation.
        deviceType:
          name: Device Type Analysis
          type: string
          exemplaryValues:
            - "desktop"
            - "mobile"
            - "tablet"
            - "unknown"
            - "generic"
          description: |
            Sophisticated device type classification system.
            Analyzes screen characteristics (screen.width/height), touch support (navigator.maxTouchPoints), and input capabilities.
            Expected to show natural device type patterns (desktop, mobile, tablet) with capability-specific variations.
          abuseIndication:
            bot: |
              Device type claiming desktop with touch support indicates automated browser.
              Type inconsistent with screen characteristics suggests automated environment.
              Generic or missing type information indicates potential automation.
        deviceVendor:
          name: Vendor Analysis
          type: string
          exemplaryValues:
            - "Dell"
            - "Apple"
            - "Samsung"
            - "Generic"
            - "VMware"
          description: |
            Advanced device vendor identification system.
            Combines hardware information (navigator.vendor), platform detection, and vendor-specific checks.
            Expected to show specific vendor patterns (Apple, Samsung, Dell) with device-specific variations.
          abuseIndication:
            bot: |
              Vendor name containing 'Generic' or missing information indicates automated browser.
              Vendor inconsistent with device type suggests automated environment.
              Unsupported vendor for claimed device indicates potential automation.
    fingerprint:
      name: Fingerprint Analysis
      type: number
      exemplaryValues:
        - 1922925364
        - 1922925364
        - 1333925364
      description: |
        Sophisticated fingerprint generation system creating unique identifiers from multiple browser characteristics.
        Combines browser information (navigator.userAgent), device details (screen.width/height), system capabilities, and feature support.
        Expected to show natural variation patterns across different browsers and devices (changes every 24-48 hours).
      abuseIndication:
        bot: |
          Fingerprint changing more frequently than every 5 minutes indicates automated browser.
          Fingerprint pattern matching known automation tools suggests automated environment.
          Generic or missing fingerprint indicates potential automation.
      outputs:
        hashStability:
          name: Hash Stability Analysis
          type: boolean
          exemplaryValues:
            - true
            - false
          description: |
            Indicates if fingerprint hash remains stable across sessions.
            Expected: natural variation for legitimate browsers (changes every 24-48 hours).
            Virtual machines often show perfect stability or frequent changes.
          abuseIndication:
            bot: |
              Perfect hash stability across different browsers indicates automated browser.
              Unnatural variation patterns suggest automated environment.
        componentMatch:
          name: Component Pattern Matching
          type: string
          exemplaryValues:
            - "legitimate_browser"
            - "selenium_automation"
            - "puppeteer_automation"
            - "playwright_automation"
            - "cypress_automation"
          description: |
            Matches fingerprint patterns against known automation tools.
            Expected: no matches for legitimate browsers.
            Common patterns include 'selenium', 'puppeteer', 'playwright', and 'cypress'.
          abuseIndication:
            bot: |
              Pattern matching 'selenium' or 'puppeteer' indicates automated browser.
              Generic pattern matching suggests automated environment.
    browserSpoofed:
      name: Browser Spoofing Analysis
      type: boolean
      exemplaryValues:
        - false
        - true
      description: |
        Advanced browser spoofing detection system.
        Analyzes version consistency (parseInt vs split), engine compatibility, and feature support claims.
        Combines multiple detection methods (navigator.userAgent, navigator.vendor) for maximum reliability.
      abuseIndication:
        bot: |
          Browser version inconsistent with user agent claims indicates automated browser.
          Engine version mismatches with browser version suggest automated environment.
          Feature support claims inconsistent with version indicate potential automation.
      outputs:
        versionMatch:
          name: Version Consistency
          type: boolean
          exemplaryValues:
            - true
            - false
          description: |
            Verifies version consistency across browser components.
            Expected: true for legitimate browsers.
            Checks major.minor.build format and compatibility.
          abuseIndication:
            bot: |
              Version inconsistencies indicate automated browser.
              Perfect version consistency suggests automated environment.
        featureMatch:
          name: Feature Support Analysis
          type: boolean
          exemplaryValues:
            - true
            - false
          description: |
            Verifies feature support claims with browser version.
            Expected: true for legitimate browsers.
            Checks API availability and compatibility.
          abuseIndication:
            bot: |
              Feature support inconsistent with version indicates automated browser.
              Unnatural feature patterns suggest automated environment.
