// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssqhxvxdxghrxthxdojc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcWh4dnhkeGdocnh0aHhkb2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODg0OTksImV4cCI6MjA2MDU2NDQ5OX0.CPwNQXenUwDqC9qpAAeGiE6WzdQxneX6dTVNDLAPszg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);